/*
    Problem 2: Even Fibonacci Numbers

    Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    By starting with  and , the first  terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
    find the sum of the even-valued terms.
 */


const MAX_FIB_VALUE: u32 = 4_000_000;

pub fn problem_2() {
    let mut term_1:u32 = 1;
    let mut term_2:u32 = 2;

    let mut sum_even_values = 0;

    while term_2 < MAX_FIB_VALUE {
        if term_2 % 2 == 0 {
            sum_even_values += term_2;
        }

        let temp = term_1;
        term_1 = term_2;

        term_2 += temp;
    }

    println!("{sum_even_values}");
}

